# Generated by Django 4.2.2 on 2023-07-24 13:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("name", models.CharField(max_length=156)),
                ("position", models.CharField(max_length=156)),
                ("fb", models.CharField(blank=True, max_length=156, null=True)),
                ("insta", models.CharField(blank=True, max_length=156, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=156, null=True)),
                ("image", models.ImageField(upload_to="SEO")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="SEO")),
                ("name", models.CharField(max_length=156)),
                ("position", models.CharField(max_length=156)),
                ("fb", models.CharField(max_length=156)),
                ("insta", models.CharField(max_length=156)),
                ("twitter", models.CharField(max_length=156)),
                ("youtube", models.CharField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="SEO")),
                ("name", models.CharField(max_length=156)),
                ("position", models.CharField(max_length=156)),
                ("review", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("h1", models.CharField(max_length=156)),
                ("slug", models.CharField(blank=True, max_length=1256, null=True)),
                ("page_name", models.CharField(blank=True, max_length=1256, null=True)),
                ("keyword", models.CharField(max_length=156)),
                ("description", models.CharField(max_length=900)),
                ("title", models.CharField(max_length=156)),
                ("breadcrumb", models.CharField(max_length=156)),
                (
                    "canonical",
                    models.CharField(
                        default="https://straightlinesource.com/", max_length=900
                    ),
                ),
                ("og_type", models.CharField(max_length=156)),
                ("og_card", models.CharField(max_length=156)),
                ("og_site", models.CharField(max_length=156)),
                ("image", models.ImageField(upload_to="SEO")),
                ("updated", models.DateField(auto_now=True)),
                (
                    "blog_banner_lg",
                    models.ImageField(blank=True, null=True, upload_to="Page Data"),
                ),
                (
                    "blog_banner_sm",
                    models.ImageField(blank=True, null=True, upload_to="Page Data"),
                ),
                ("published", models.DateField()),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "edits",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("schema", models.TextField(blank=True, max_length=15622, null=True)),
                (
                    "guide_image",
                    models.ImageField(blank=True, null=True, upload_to="Page Data"),
                ),
                (
                    "guide",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.author"
                    ),
                ),
                ("category", models.ManyToManyField(to="home.category")),
                ("tag", models.ManyToManyField(to="home.tags")),
            ],
        ),
    ]
